version: "3"
services:
  fastapi:
    build: .
    command: uvicorn fastapi.app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  celery:
    build: .
    command: celery -A src.config.celery_config.celery_app worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
